joint_groups:
  arm:
    joints:
      - joint1
      - joint2
    sync_read:
      - position
    sync_write:
      - position
joint1: { id: 2, dynamixel: "XL330", operating_mode: 3 }
joint2: { id: 3, dynamixel: "XL330", operating_mode: 3 }

